chaloBEST/urls.py
from django.conf.urls.defaults import *
import settings
from os.path import join
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from feeds import RouteFeed
#import ox.django.api.urls
#import mumbai
from users.forms import SignupFormExtra 


urlpatterns = patterns('',
    # Example:
    # (r'^chaloBEST/', include('chaloBEST.foo.urls')),
#    url(r'^$','mumbai.views.index', name='index'),
    url(r'^$','mumbai.views.index', name='index'),

    url(r'^about$', 'mumbai.views.about', name='about'),
    url(r'^android$', 'mumbai.views.android', name='android'),
    url(r'^contact$', 'mumbai.views.contact', name='contact'),
    url(r'^join_us$', 'mumbai.views.join_us', name='join_us'),
    url(r'^sms$', 'mumbai.views.sms', name='sms'),
    url(r'^stats/$','mumbai.views.stats', name='stats'),
    url(r'^tweety/$','views.tweety', name='tweety'),
    url(r'^autocomplete/$', 'mumbai.views.autocomplete', name='autocomplete'),
#    url(r'^static/(?P<path>.*)$','django.views.static.serve', {'document_root':'./static'}),
    (r'^routes/$', 'mumbai.views.routes'),
    (r'^route/(?P<code>[a-zA-Z0-9\s\-]*?)/$', 'mumbai.views.route'),
    (r'^route/(?P<code>[a-zA-Z0-9\s\-]*?)/georss/$', RouteFeed()),
    (r'^areas/$', 'mumbai.views.areas'),
    (r'^area/(?P<slug>.*?)/$', 'mumbai.views.area'),
#    (r'^area/(?P<name>.*?)/georss/$', AreaFeed()),
    (r'^stop/(?P<slug>.*?)/$', 'mumbai.views.stop'),
#    (r'^stop/(?P<slug>.*?)/georss/$', StopFeed()),
    (r'^buseditor/$', 'mumbai.views.buseditor'),	   
    (r'^editstops/$', 'mumbai.views.editstops'),
    #(r'^accounts/', include('allauth.urls')),
    (r'^1.0/', include('mumbai.apiurls')),
    (r'^route/freq/(?P<code>.*)$', 'mumbai.views.route_headway'), 
    #url(r'^login/', include('socialregistration.urls',namespace='socialregistration')),                                        
    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #(r'^grappelli/', include('grappelli.urls')),
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^matchstops/$', 'mumbai.views.fuzzystops'),
    (r'^fuzzystops_edit/$', 'mumbai.views.fuzzystops_edit'),
# url(r'^accounts/', include('userena.urls')),
 url(r'^accounts/signup/$', 
		'userena.views.signup',
      		{'signup_form': SignupFormExtra}),
 url(r'^accounts/', include('userena.urls')),
 
     url(r'^messages/',include('userena.contrib.umessages.urls')),

    
)

if settings.LOCAL_DEVELOPMENT:
#
  urlpatterns += patterns('',
#
  (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': join(settings.PROJECT_ROOT, "static")}),
  (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': join(settings.PROJECT_ROOT, "media")}),
#
)

chaloBEST/mumbai/models.py
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django import forms
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.db import connection
import json
from django.contrib.gis.measure import D
import datetime
from gtfs.gtfs_export import time_of

STOP_CHOICES = ( ('U','Up'),
                 ('D', 'Down'),
                 )

DAYS = {
    1: 'Monday',
    2: 'Tuesday',
    3: 'Wednesday',
    4: 'Thursday',
    5: 'Friday',
    6: 'Saturday',
    7: 'Sunday',
    8: 'Holiday'
    }

SCHED = {
    'MS':[1, 2, 3, 4, 5, 6],
    'HOL':[7, 8],
    'SUN':[7],
    'MF&HOL':[1, 2, 3, 4, 5, 8],
    'SAT':[6],
    'MF':[1, 2, 3, 4, 5],
    'SH':[7, 8],
    'AD':[1, 2, 3, 4, 5, 6, 7, 8],
    'SAT&SUN':[6, 7],
    'MS&HOL':[1, 2, 3, 4, 5, 6, 8],
    'FW':[1, 2, 3, 4, 5, 6, 7],
    'MS&SUN':[1, 2, 3, 4, 5, 6, 7],
    'SAT/SH':[6, 7, 8],
    'SAT&HOL':[6, 8],
    'SAT/HOL':[6, 8],
    'SAT&SH':[6, 7, 8],
    'SAT/SUND&HOL':[6, 7, 8],
    'S/H':[7, 8],
    'SUN/HOL':[7, 8],
    'SAT,SUN&HOL':[6, 7, 8],
    'FH':[5, 8],
    'Hol':[8,]
    }






# Runtime start and end hour
# matching column `runtime$` where `$` = index % 4 + 1
RUNTIMES = (
    (00, 07), 
    (07, 11),
    (11, 17),
    (17, 20),
    (20, 24)
)

class TrigramSearchManager(models.GeoManager):
    def __init__(self, trigram_columns=[]):
        super(TrigramSearchManager, self).__init__()
        self.trigram_columns = trigram_columns

    def set_threshold(self, threshold):
        """Set the limit for trigram similarity matching."""
        cursor = connection.cursor()
        cursor.execute("""SELECT set_limit(%f)""" % threshold)

    def find_approximate(self, text, match=0.5):
        self.set_threshold(match)
        similarity_measure = "greatest(%s)" % ",".join(["similarity(%s, %%s)" % col for col in self.trigram_columns])
        similarity_filter = " OR ".join(["%s %%%% %%s" % col for col in self.trigram_columns])
        text_values = [text] * len(self.trigram_columns)
        qset = self.get_query_set()
        # use the pg_trgm index via the % operator
        qset = qset.extra(select={"similarity":similarity_measure},
                          select_params=text_values,
                          where=[similarity_filter],
                          params=text_values,
                          order_by=["-similarity"])
        return qset

class Area(models.Model):
    objects = TrigramSearchManager(("name", "name_mr", "display_name"))
    code = models.IntegerField() #primary_key=True)
    slug = models.SlugField(null=True)
    name = models.TextField(blank=True, max_length=255)
    name_mr= models.TextField(null=True, blank=True, max_length=512) #null=True, 
    display_name = models.TextField(blank=True, max_length=255)
    geometry = models.PolygonField(blank=True, null=True)
    alt_names = generic.GenericRelation("AlternativeName")

    def get_dict(self):
        return {
            'id': self.id,
            'code': self.code,
            'slug': self.slug,
            'name': self.name,
            'name_mr': self.name_mr,
            'display_name': self.display_name,
            'url': self.get_absolute_url()
            #FIXME add alt_names and geometry
        }

    
    def get_autocomplete(self):
        '''
        Returns a dict to be used by the autocomplete front-end
        '''
        return {
            'id': self.id,
            'type': 'Area',
            'title': self.display_name,
            'url': self.get_absolute_url()
        }

    def get_absolute_url(self):
        return "/area/%s/" % self.slug

    def __unicode__(self):
        return self.name   

    #FIXME: ideally this would be done using the polygon of the area, but right now we take a random stop in the area, find all stops within x kms, and then return unique areas for those stops.    
    @property
    def nearby_areas(self, distance=D(km=3)):
        stop = self.stop_set.all()[0]
        tup = (stop.point, distance,)
        qset = Stop.objects.filter(point__distance_lte=tup).values('area').distinct()
        area_ids = [val['area'] for val in qset]
        return Area.objects.filter(pk__in=area_ids)    

    @property
    def routes_passing(self):
        return Route.objects.filter(routedetail__stop__area=self).distinct()
        

class Road(models.Model):
    code = models.IntegerField()#primary_key=True)
    slug = models.SlugField(null=True)
    name = models.TextField(blank=True, max_length=255)
    name_mr= models.TextField(null=True, blank=True, max_length=512)
    display_name = models.TextField(blank=True, max_length=255)
    geometry = models.LineStringField(blank=True, null=True)
    alt_names = generic.GenericRelation("AlternativeName")

    def __unicode__(self):
        return self.name   


class Fare(models.Model):
    slab = models.DecimalField(max_digits=5, decimal_places=2) 
    ordinary = models.PositiveIntegerField()
    limited = models.PositiveIntegerField()
    express = models.PositiveIntegerField()
    ac = models.PositiveIntegerField()
    ac_express = models.PositiveIntegerField()
    def __unicode__(self):
        return str(self.slab)   

class Stop(models.Model):
    objects = TrigramSearchManager(("name", "name_mr", "display_name"))
    code = models.IntegerField(db_index=True)
    slug = models.SlugField(null=True)
    name = models.TextField(blank=True, max_length=255, db_index=True)
    display_name = models.TextField(blank=True, max_length=255)
    dbdirection = models.CharField(null=True, blank=True, max_length=5, choices=STOP_CHOICES) #stopfl - > direction
    chowki = models.NullBooleanField(null=True, blank=True) # this is nullable since in the next datafeed , they might have blank to represent a 0.
    road = models.ForeignKey(Road, default=None, null=True, blank=True)
    area = models.ForeignKey(Area, default=None, null=True, blank=True)
    depot = models.ForeignKey("Depot", default=None, null=True, blank=True, related_name="is_depot_for") #models.CharField(null=True, blank=True, max_length=5)
    name_mr= models.TextField(null=True, blank=True, max_length=512)#null=True
    point = models.PointField(null=True)
    alt_names = generic.GenericRelation("AlternativeName")

    def get_autocomplete(self):
        '''
        Returns a dict to be used by the autocomplete front-end
        '''
        return {
            'id': self.id,
            'type': 'Stop',
            'title': "%s (%s)" % (self.display_name, self.area.display_name,),
            'url': self.get_absolute_url()
        }

    def get_routes(self):
        routes = []
        for r in self.routedetail_set.all():
            if r.route is not None:
                routes.append(r.route)
        return routes        

    def get_dict(self):
        #routes = self.get_routes()
        return {
            'id': self.id,
            'code': self.code,
            'slug': self.slug,
            'official_name': self.name,
            'display_name': self.display_name,
            'road': self.road.display_name,
            'road_mr': self.road.name_mr,
            'area': self.area.display_name,
            'area_mr': self.area.name_mr,
            'area_url': self.area.get_absolute_url(),
            'name_mr': self.name_mr,
            'direction': self.dbdirection,
            'routes': ", ".join([r.display_name for r in self.routes]),
            'alternative_names': ", ".join([a.name for a in self.alt_names.all()]),
            'url': self.get_absolute_url()
        }

    def get_geojson(self, srid=4326):
#        print srid
        if self.point is not None:
            geom = json.loads(self.point.transform(srid, True).geojson)
        else:
            geom = {}

        properties = self.get_dict()

        return {
            'type': 'Feature',
            'properties': properties,
            'geometry': geom
        }        

    def from_geojson(self, geojson, srid=4326):
        geom = geojson['geometry']['coordinates']
        data = geojson['properties']
        point = Point(geom[0], geom[1], srid=srid).transform(4326, True)
        if point:
            self.point = point
        self.display_name = data['display_name']
        self.name_mr = data['name_mr']
        if data.has_key('alternative_names') and data['alternative_names'].strip() != '':
            for a in self.alt_names.all():
                a.delete()
            for a in data['alternative_names'].split(","):
                alt_name = AlternativeName()
                alt_name.name = a.strip()
                alt_name.typ = 'common'
                alt_name.content_object = self
                alt_name.save()
                self.alt_names.add(alt_name)    
        self.save()
        return self.get_geojson(srid=srid)

    @property
    def nearby_stops(self, dist=D(km=0.5)):
        tup = (self.point, dist,)
        return Stop.objects.filter(point__distance_lte=tup)

    @property
    def routes(self):
        return Route.objects.filter(routedetail__stop=self)

    @property    
    def display_alt_names(self):
        '''
            Exclude the display_name from the alt name results and return alt names
        '''
        alt_names = []
        for a in self.alt_names.all():
            if a.name != self.display_name:
                alt_names.append(a)
        return alt_names

    def __unicode__(self):
        return self.name   

    ''' 
    check if point exists for stop
    '''
    def has_point(self):        
        if self.stoplocation_set.all():
            return True
        else:
            return False
        
    has_point.boolean = True

    def get_absolute_url(self):
        return "/stop/%s" % self.slug


#Code, prefix, suffix, aliases
ROUTE_TYPES = (
    (0, "", "", ""), #Ordinary
    (1, "", " Ltd", "L, Limited, Ltd"), #Limited
    (2, "", "", "Extra"), #Ordinary Extra

chaloBEST/users/models.py
from django.db import models
from django.contrib.auth.models import User
from userena.models import UserenaBaseProfile
from userena.models import UserenaLanguageBaseProfile
#from django.contrib.auth.models import User
#from django.contrib.auth.models import User
#from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
import datetime

# Create your models here.
class UserProfile(UserenaLanguageBaseProfile):
	GENDER_CHOICES =(
		(1, _('Male')),
		(2, _('Female')),
	)

#	user = models.ForeignKey(User, unique=True)
#	url - models.URLField("Website", blank=True)
#	company = models.CharField(max_length=50, blank=True)
	user =  models.ForeignKey(User,
				    unique=True,
				    verbose_name =('user'),
				    related_name = 'profile')
	gender = models.PositiveSmallIntegerField(_('gender'),
						 choices=GENDER_CHOICES,
						 blank = True,
						null=True)
	website = models.URLField(_('website'), blank=True)
	location = models.CharField(_('location'), max_length=255, blank=True)
	birth_date = models.DateField(_('birth date'), blank=True, null=True)
#	about_me = models.TextField(_('about me'), blank = True)
	mobile_number = models.CharField(_('mobile number'), blank = True, max_length=10)
	about_me = models.TextField(_('about me'), blank = True)

	@property
	def age(self):
		if not self.birth_date: return False
		else:
			today = datetime.date.today()
			try:
				birthday = self.birth_date.replace(year=today.year)
			except ValueError:
				day = today.day -1 if today.day != 1 else today.day + 2
				birthday = self.birth_date.replace(year=today.year, day = day)
			if birthday > today: return today.year - self.birth_date.year - 1
			else: return today.year - self.birth_date.year
#def create_user_profile(sender, instance, created, **kwargs):
#	if created:
#		UserProfile.objects.create(user=instance)

#post_save.connect(create_user_profile, sender=User)
#def create_profile(sender, **kw):
#	user = kw["instance"]
#	if kw["created"]:
#		up = UserProfile(user=user, gender=1,location="test")
#		up.save()
#post_save.connect(create_profile, sender=User)


#User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

chaloBEST/templates/MyPage_edit.html
{% extends 'base.html' %}
{% block content %}

<!-- Settings links & profile -->
<div class="g3">
	<div class="leading20"></div>
		<div class="g3_3 staticpage main">
		<ul id="box-nav">
			<li><a href='/accounts/mcaro/'>My page</a></li>
			<li class="selected"><a href='/accounts/mcaro/edit/'>Edit profile</a></li>
			<li><a href='/accounts/mcaro/password/'>Change password</a></li>
			<li><a href='/accounts/mcaro/email/'>Change email</a></li>
		</ul>
	</div>
	<div id="box">
		<img class="mugshot" src="http://www.gravatar.com/avatar/8b8f3a7297801bd5cdbc6e58231ab0ed?s=140&amp;d=monsterid" alt="Your mugshot" />
		<dl>
			<dt>Email</dt>
			<dd>carolien.klep@gmail.com</dd>
		</dl>
	</div>
</div>

<!-- CONTENT BLOCK-->
<div class="g9">
	<div class="leading40"></div>
	<div class="g9_9 staticpage main">
		<form action="" enctype="multipart/form-data" method="post">
		<div style='display:none'><input type='hidden' name='csrfmiddlewaretoken' value='AY0UF5lQ8hGGdnN0Ei8F15O1XQP9v399' /></div>
		<fieldset>
			<h1><legend>Edit Profile</legend></h1>
	</div>
</div>
<div class="g4">
	<div class="g4_4 staticpage main"></div>
		<div class="divline">
			<div class="divlabel"><label for="id_first_name">First name:</label></div>
			<div class="divinput"><input id="id_first_name" type="text" name="first_name" maxlength="30" /></div>
		</div>
		<div class="divline">
			<div class="divlabel"><label for="id_last_name">Last name:</label></div>
			<div class="divinput"><input id="id_last_name" type="text" name="last_name" maxlength="30" /></div>
		</div>
		<div class="divline">
			<div class="divlabel"><label for="id_mugshot">Mugshot:</label></div>
			<div class="divinput"><input type="file" name="mugshot" id="id_mugshot" /> <span class="helptext">A personal image displayed in your profile.</span></div>
		</div>
		<div class="divline">
			<div class="divlabel"><label for="id_gender">Gender:</label></div>
			<div class="divinput"><select name="gender" id="id_gender">
				<option value="" selected="selected">---------</option>
				<option value="1">Male</option>
				<option value="2">Female</option>
				</select></div>
		</div>
		<div class="divline">
			<div class="divlabel"><label for="id_birth_date">Birth date:</label></div>
			<div class="divinput"><input type="text" name="birth_date" id="id_birth_date" /></div>
		</div>
		<div class="divline">
			<div class="divlabel"><label for="id_website">Website:</label></div>
			<div class="divinput"><input id="id_website" type="text" name="website" maxlength="200" /></div>
		</div>
		<div class="divline">
			<div class="divlabel"><label for="id_location">Location:</label></div>
			<div class="divinput"><input id="id_location" type="text" name="location" maxlength="255" /></div>
		</div>
</div>

<!-- CONTENT BLOCK-->
<div class="g5">
	<div class="g5_5 staticpage main">
		<div class="divline">
			<div class="divlabel"><label for="id_about_me">About me:</label></div>
			<div class="divinput"><textarea id="id_about_me" rows="8" cols="40" name="about_me"></textarea></div>
		</div>
		<div class="leading10"></div>
		<div class="divline">
			<div class="divlabel"><label for="id_language">Language:</label></div>
			<div class="divinput"><select name="language" id="id_language">
				<option value="ar">Arabic</option>
				<option value="az">Azerbaijani</option>
				<option value="bg">Bulgarian</option>
				<option value="bn">Bengali</option>
				<option value="bs">Bosnian</option>
				<option value="ca">Catalan</option>
				<option value="cs">Czech</option>
				<option value="cy">Welsh</option>
				<option value="da">Danish</option>
				<option value="de">German</option>
				<option value="el">Greek</option>
				<option value="en" selected="selected">English</option>
				<option value="en-gb">British English</option>
				<option value="eo">Esperanto</option>
				<option value="es">Spanish</option>
				<option value="es-ar">Argentinian Spanish</option>
				<option value="es-mx">Mexican Spanish</option>
				<option value="es-ni">Nicaraguan Spanish</option>
				<option value="et">Estonian</option>
				<option value="eu">Basque</option>
				<option value="fa">Persian</option>
				<option value="fi">Finnish</option>
				<option value="fr">French</option>
				<option value="fy-nl">Frisian</option>
				<option value="ga">Irish</option>
				<option value="gl">Galician</option>
				<option value="he">Hebrew</option>
				<option value="hi">Hindi</option>
				<option value="hr">Croatian</option>
				<option value="hu">Hungarian</option>
				<option value="id">Indonesian</option>
				<option value="is">Icelandic</option>
				<option value="it">Italian</option>
				<option value="ja">Japanese</option>
				<option value="ka">Georgian</option>
				<option value="kk">Kazakh</option>
				<option value="km">Khmer</option>
				<option value="kn">Kannada</option>
				<option value="ko">Korean</option>
				<option value="lt">Lithuanian</option>
				<option value="lv">Latvian</option>
				<option value="mk">Macedonian</option>
				<option value="ml">Malayalam</option>
				<option value="mn">Mongolian</option>
				<option value="nb">Norwegian Bokmal</option>
				<option value="ne">Nepali</option>
				<option value="nl">Dutch</option>
				<option value="nn">Norwegian Nynorsk</option>
				<option value="pa">Punjabi</option>
				<option value="pl">Polish</option>
				<option value="pt">Portuguese</option>
				<option value="pt-br">Brazilian Portuguese</option>
				<option value="ro">Romanian</option>
				<option value="ru">Russian</option>
				<option value="sk">Slovak</option>
				<option value="sl">Slovenian</option>
				<option value="sq">Albanian</option>
				<option value="sr">Serbian</option>
				<option value="sr-latn">Serbian Latin</option>
				<option value="sv">Swedish</option>
				<option value="sw">Swahili</option>
				<option value="ta">Tamil</option>
				<option value="te">Telugu</option>
				<option value="th">Thai</option>
				<option value="tr">Turkish</option>
				<option value="tt">Tatar</option>
				<option value="uk">Ukrainian</option>
				<option value="ur">Urdu</option>
				<option value="vi">Vietnamese</option>
				<option value="zh-cn">Simplified Chinese</option>
				<option value="zh-tw">Traditional Chinese</option>
			</select></div>
		</div>
		<div class="divline">
			<div class="divlabel"><label for="id_privacy">Privacy:</label></div>
			<div class="divinput">
				<select name="privacy" id="id_privacy">
					<option value="open">Open</option>
					<option value="registered" selected="selected">Registered</option>
					<option value="closed">Closed</option>
				</select> <span class="helptext">Designates who can view your profile.</span></div>
		</div>
		 </fieldset>
		<div class="leading10"></div>
		<div class="divline">
			<div class="divlabel">&nbsp;</div>
			<div class="divinput"><input class="actionbutton" type="submit" value="Save changes" /></div>
		</div>
		 
		</form>
	</div>
	<div class="leading40"></div>
</div>

{% endblock %}

chaloBEST/templates/index.html
{% extends 'base.html' %}

{% block extra_head %}
<link rel="stylesheet" href="/static/leaflet/minimap/Control.MiniMap.css" />
<script src="/static/leaflet/minimap/Control.MiniMap.js"></script>
<script src="/static/js/index.js"></script>

{% endblock %}

{% block content %}

<style type="text/css">
    .listtitle {
        padding-top: 0;
}
</style>

<script type="text/html" id="stopTemplate">

<tr class="listItem stopRow" data-id="<%= stop.id %>">
	<td class="twoCol_wide"><a href="<%= stop.url %>"><b><%= stop.display_name %></b><br /><span><%= stop.name_mr %></span></a></td>
    <td class="twoCol_narrow"><a href="<%= stop.area_url %>"><b><%= stop.area %></b><br /><span><%= stop.area_mr %></span></a></td>
</tr>
</script>

		<div class="g12 search">
<!--			<div class="g9_1">&nbsp;</div>-->
			<div class="g12_7">
				<h1 style="display:none">ChaloBEST Mumbai busguide</h1>
				{% include 'guidesearch_form.html' %}
			</div>


		<div class="searchbar g12_5">
			<div class="g12_12">
				<ul>
					<li><span class="statistics">{{ counts.areas }} AREAS </span>
						
							<img class="statsImg" src="/static/images/area.png" >
						
					</li>
					<li><span class="statistics">{{ counts.stops }} STOPS</span><img class="statsImg" src="/static/images/stop.png" ></li>
					<li><span class="statistics">{{ counts.routes }} ROUTES</span><img class="statsImg" src="/static/images/bus.png" ></li>
				</ul>
			</div>
		</div>


		</div>

<div class="g7">

	<div class="leading10"></div>

	<div class="g7_7 white">

		<div class="g9_9 maphome">
            <div class="landingmap" id="map"></div>
		</div>
		<br style="clear: both;" />
	</div>

	<div class="g9_9">&nbsp;
	<!--
		<div class="listtitlesmall">
			<h3>Comments</h3>
		</div>
		<div class="comments" id="comments_list">
			<div class="comment_item">
				<div class="comment_user">
					indrani misra:
				</div>
				<div class="comment_content">
					Bani,
					Loved reading your article. What a lovely and meaningful experience between the banyan trees! I could picture it all. carry on with the great work that SRUTI is doing. Between the great economic and social divide...
				</div>
			</div>
		</div>
		<div class="leading20"></div>
		<div class="comments" id="comment_form">
			<h4 class="formHeader">Leave a comment</h4>
			<form action="/comments/post/" method="POST">
				<div style='display:none'>
					<input type='hidden' name="" value="" />
					<input type="hidden" name="next" value="" />
				</div>
				<div class="box">
					<label for="id_name">Name:</label>
					<div class="textbox"><input id="id_name" type="text" name="name" maxlength="50" /></div>
				</div>
				<div class="box">
					<label for="id_email">Email address:</label>
					<div class="textbox"><input id="id_email" type="text" name="email"  /></div>
				</div>
				<div class="box">
					<label for="id_url">URL:</label>
					<div class="textbox"><input id="id_url" type="text" name="url" /></div>
				</div>
				<div class="box">
					<label for="id_comment">Comment:</label>
					<div class="textbox"><textarea id="id_comment" rows="10" cols="40" name="comment"></textarea></div>
				<div class="pot">
					<label for="id_honeypot">If you enter anything in this field your comment will be treated as spam:</label>
					<input type="text" name="honeypot" id="id_honeypot" />
				</div>
				<div class="box right">
					<input type="hidden" name="content_type" value="emailer.emailerissue" id="id_content_type" />
					<input type="hidden" name="object_pk" value="" id="id_object_pk" />
					<input type="hidden" name="timestamp" value="" id="id_timestamp" />
					<input type="hidden" name="security_hash" value="" id="id_security_hash" />
					<div class="g9_3">&nbsp;</div>
					<div class="g9_gut"></div>
					<div class="g9_6"><input type="submit" id="id_submit" name="post" class="submit-post" value="Post"></div>
				</div>
			</form>
		</div>
		</div> -->
	</div>
</div>
<!-- 
<div class="g3">
	<div class="g3_3">
		<div class="highlight">
			<h2>Trip planner</h2>
			<div class="tripform">
				<form name="homeOTPsearch">
					<input class="tripinput" type="text" name="from" value="Type departure location" />
					<input class="tripinput" type="text" name="to" value="Type arrival location" />
					<input class="submit" type="submit" value="Search" />
					<br style="clear: both;" />
				</form>
			</div>
		</div>
	</div>
</div>
 -->
 
<div class="g5">
	<div class="leading20">&nbsp;</div>
	<div class="g5_5 listtitle">
		
		<h2><img src="/static/images/stop.png" />Displayed stops</h2>
		</div>
	<div class="g5_5 height">
		<div class="g5_5 list">
			<table name="landing_area" class="tablebase stopsTable" id="nearStopsTable">
				<tr class="sublist">
					<th colspan="2">
						<form name="filter_home_area" class="listfilter_form">
							<input class="listfilter_input" type="text" name="filter list" placeholder="Type to filter, select below..." />
						</form>
					</th>
					<!-- <th class="twoCol_narrow"></th> -->
				</tr>
				<tr class="sublist">
					<th class="twoCol_wide">
						<span class="col_img"><img src="/static/images/stop.png" alt="Stop" title="Stop" /> Stop</span>
					</th>
					<th class="twoCol_narrow" alt="Route filter" title="Route filter">
						<span class="col_img"><img src="/static/images/area.png" alt="Area" title="Area" /> Area</span>
					</th>
				</tr>

			</table>
		</div>
	</div>
</div>

{% endblock content %}